### ISSUE TITLE
test

### ISSUE THREAD

**Issue by tatsuzawamoriyasu** [tatsuzawamoriyasu/kaggle_titanic#1]
# 開発ドキュメント
[etl core](https://github.com/cancerscan/etl_core/wiki/%E3%83%87%E3%83%BC%E3%82%BF%E3%82%BD%E3%83%BC%E3%82%B9%E7%94%A8%E3%83%AA%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA-%E9%96%8B%E7%99%BA%E3%83%89%E3%82%AD%E3%83%A5%E3%83%A1%E3%83%B3%E3%83%88)

# FKAC167
仕様書のP67〜68
[2_設計-基本-0334_VER4.1_突合データ出力（ＣＳＶ）基本設計書.xls](https://cancerscan.app.box.com/file/691756187940?s=irtj2el9qgxo357sylr4fff9z7lmai3c)

<img width="754" alt="スクリーンショット 2022-07-25 13 37 32" src="https://user-images.githubusercontent.com/67680583/180699703-8d37f37f-1faa-49e0-add7-7202cfcf7ded.png">

# ToDo

- [ ] ①データの命名規則を決定する
- [ ] ②transformのvalidationを決める
- [ ] ③標準のTransform処理を実装する
- [ ] ④extractのvalidationを決める
- [ ] ⑤標準のextractを実装する
- [ ] ⑥動作確認を行う

# ①データの命名規則を決定する
- [] 命名は既に `etl/source/tokutei/` で実装されている名称を、ここに無いものは[旧データ基盤のmerged_receipt_3.json](https://github.com/cancerscan/data-platform/blob/master/bigquery/raw/tables/merged_receipt_3.json)で使用されている名称を使用（一部追記する可能性あり）

# ②transformのvalidationを決める
[2_設計-基本-0334_VER4.1_突合データ出力（ＣＳＶ）基本設計書.xls](https://cancerscan.app.box.com/file/691756187940?s=irtj2el9qgxo357sylr4fff9z7lmai3c)
P67〜68
詳細は[スプレッドシート](https://docs.google.com/spreadsheets/d/1I_vS6I-UlkSL9cXd0D6AdIyOUuEpCN8lmU1AN-7qoKY/edit#gid=820104706)にまとめている

# ③標準のTransform処理を実装する
医療レセプト管理→medical_receipt_management
- [ ] `etl/source/tokutei/medical_receipt_management/transform.py`に実装する

# ④extractのvalidationを決める
- [ ] 仕様書で定義されているヘッダーレコードがレコード一行目にあるか

# ⑤標準のextractを実装する
医療レセプト管理→medical_receipt_management
- [ ] `etl/source/tokutei/medical_receipt_management/extract.py`に実装する

# ⑥動作確認を行う
- [ ] ローカルでテストを実装する
